#!/bin/bash

# Help page
showHelp() {
    cat << EOF

Cross validation workflow of TensorLy

Usage: ./tensorlycv -i <input-file> -o <output-directory> [--cores/--rank/--trials/--iters/--ratio/--memgb/-l/-h/-v]

    -i, -input,   --input         Input file (e.g., data/vaccine_tensor.npy, mandatory)

    -o, -outdir,  --outdir        Output directory (e.g., output, mandatory)

    -c, -cores,   --cores         Number of cores used in Snakemake (e.g., default values is 10, optional)

    -r, -rank,    --rank          Maximum rank parameter to search (e.g., default value is 10, optional)

    -t, -trials,  --trials        Number of random trials (e.g., default value is 50, optional)

    -e, -iters,   --iters         Number of iterations (e.g., default value is 1000, optional)

    -a, -ratio,   --ratio         Sampling ratio of cross validation (0 - 100, e.g., default value is 20, optional)

    -m, -memgb,   --memgb         Memory usage (GB, e.g. default value is 10, optional)

    -l, -cluster, --cluster       Cluster option of Snakemake (e.g., "qsub -l nc=4 -p -50 -r yes", optional)

    -h, -help,    --help          Display help

    -v, -version, --version       Version of this workflow

EOF
}

# Default Values
INPUT=""
OUTDIR=""
CORES=10
RANK=10
TRIALS=50
ITERS=1000
RATIO=20
MEMGB=10
CLUSTER=""
VERSION="v1.1.0"

# Command Argument Parsing
while getopts i:o:c:r:t:e:a:m:l:h-:v- opt; do
	optarg="$OPTARG"
	[[ "$opt" = - ]] &&
	    opt="-${OPTARG%%=*}" &&
	    optarg="${OPTARG/${OPTARG%%=*}/}" &&
	    optarg="${optarg#=}"
    case "-$opt" in
        -i|--input)
            INPUT="$optarg"
            ;;
        -o|--outdir)
            OUTDIR="$optarg"
            ;;
        -c|--cores)
            CORES="$optarg"
            ;;
        -r|--rank)
            RATIO="$optarg"
            ;;
        -t|--trials)
            TRIALS="$optarg"
            ;;
        -e|--iters)
            ITERS="$optarg"
            ;;
        -a|--ratio)
            RATIO="$optarg"
            ;;
        -m|--memgb)
            MEMGB="$optarg"
            ;;
        -l|--cluster)
            CLUSTER="$optarg"
            ;;
        -h|--help)
            showHelp
            exit 0
            ;;
        -v|--version)
            echo $VERSION
            exit 0
            ;;
        \?)
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

# Perform Snakemake Workflow
if [ "$CLUSTER" == "" ]; then
	snakemake -j $CORES --config input=$INPUT outdir=$OUTDIR \
	rank=$RANK trials=$TRIALS iters=$ITERS ratio=$RATIO \
	--resources mem_gb=$MEMGB \
    --use-singularity \
    --latency-wait 60
else
	snakemake -j $CORES --config input=$INPUT outdir=$OUTDIR \
	rank=$RANK trials=$TRIALS iters=$ITERS ratio=$RATIO \
	--resources mem_gb=$MEMGB \
    --use-singularity \
    --latency-wait 60 \
	--cluster "$CLUSTER"
fi
