name: Docker Pull/Run (koki/tensorlycv_component)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
    unit-test-job:
        name: run unit-test job
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: docker run
              run: |
                  docker run koki/tensorlycv_component:latest python -c "import numpy; import pandas; import tensorly; import matplotlib; import seaborn; import snakemake"
