name: Docker Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
    unit-test-job:
        name: run unit-test job
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: docker run
               run: docker run -it --rm koki/tensorlycv_component:latest python -c "import sys; import numpy as np; import pandas as pd; import tensorly.decomposition as tsd; import pickle as pkl; import matplotlib.pyplot as plt; import seaborn as sns; import math; import random as rd"
