name: Docker Run (tensorlycv)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
    wget:
        name: wget
        runs-on: ubuntu-latest
        steps:
            - name: wget
        uses: wei/wget@v1
        with:
            args: -O data/vaccine_tensor.npy https://figshare.com/ndownloader/files/38344040

jobs:
    unit-test-job:
        name: run unit-test job
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: src/test.sh
              run: |
                  src/test.sh
